// Generated by CoffeeScript 1.7.1
(function() {
  this.Ball = (function() {
    var HEIGHT, WIDTH;

    WIDTH = 10;

    HEIGHT = 10;

    function Ball(x, y) {
      this.x = x;
      this.y = y;
      this.vel_x = 5;
      this.vel_y = 5;
    }

    Ball.prototype.draw = function(context) {
      return context.fillRect(this.x, this.y, 10, 10);
    };

    return Ball;

  })();

}).call(this);
