// Generated by CoffeeScript 1.7.1
(function() {
  var canvas, context, draw, main_loop, playerPaddle, update;

  canvas = document.getElementById("game");

  context = canvas.getContext("2d");

  playerPaddle = new Paddle("Player", "#ACB3A7");

  update = function() {};

  draw = function() {
    context.clearRect(0, 0, canvas.width, canvas.height);
    return playerPaddle.draw(context);
  };

  main_loop = function() {
    update();
    draw();
    return window.requestAnimationFrame(main_loop);
  };

  window.requestAnimationFrame(main_loop);

}).call(this);
