// Generated by CoffeeScript 1.7.1
(function() {
  var add_event_listeners, canvas, context, draw, keys, main_loop, playerPaddle, update;

  canvas = document.getElementById("game");

  context = canvas.getContext("2d");

  playerPaddle = new Paddle("Player", "#ACB3A7", 10, canvas.height / 2 - Paddle.HEIGHT);

  keys = [];

  update = function() {
    if (keys[38]) {
      if (playerPaddle.y >= 0) {
        return playerPaddle.y -= 3;
      }
    } else if (keys[40]) {
      if (playerPaddle.y <= (canvas.height - Paddle.HEIGHT)) {
        return playerPaddle.y += 3;
      }
    }
  };

  draw = function() {
    context.clearRect(0, 0, canvas.width, canvas.height);
    return playerPaddle.draw(context);
  };

  main_loop = function() {
    update();
    draw();
    return window.requestAnimationFrame(main_loop);
  };

  add_event_listeners = function() {
    document.body.addEventListener('keydown', function(e) {
      return keys[e.keyCode] = true;
    });
    return document.body.addEventListener('keyup', function(e) {
      return keys[e.keyCode] = false;
    });
  };

  add_event_listeners();

  window.requestAnimationFrame(main_loop);

}).call(this);
