// Generated by CoffeeScript 1.7.1
(function() {
  this.Paddle = (function() {
    Paddle.WIDTH = 10;

    Paddle.HEIGHT = 50;

    function Paddle(name, colour, x, y) {
      this.name = name;
      this.colour = colour;
      this.x = x;
      this.y = y;
      this.width = 10;
      this.height = 50;
    }

    Paddle.prototype.draw = function(context) {
      context.fillStyle = this.colour;
      return context.fillRect(this.x, this.y, Paddle.WIDTH, Paddle.HEIGHT);
    };

    return Paddle;

  })();

}).call(this);
