// Generated by CoffeeScript 1.7.1
(function() {
  this.Paddle = (function() {
    function Paddle(name, colour) {
      this.name = name;
      this.colour = colour;
    }

    Paddle.prototype.draw = function(context) {
      context.fillStyle = this.colour;
      return context.fillRect(20, 20, 20, 20);
    };

    return Paddle;

  })();

}).call(this);
